### ISSUE TITLE
prefer-template ??

### ISSUE THREAD

**Issue by maranomynet** [hugsmidjan/hxmstyle#11]
Something to break your minds:

```js
const bar = {
  valueOf() { return 'A' },
  toString() { return 'B' },
}

console.log('foo' + bar === `foo${bar}`);   // false 🤔
console.log(`foo${bar}`);   // "fooB"
console.log('foo' + bar);   // "fooA" 🤯
```

Old-style string concatenation using the `+` operator, prefers `.valueOf()` over `.toString()`

::table_flip::

So, we might want to consider adding https://eslint.org/docs/latest/rules/prefer-template in the next **major** version.

**Comment by Valur** [comment]
Yea, I think this is a pretty good change.
I have an active branch that will probably be v8. Can add this there

**Comment by maranomynet** [comment]
Let's try it!
Pushed to `canary`: https://github.com/hugsmidjan/hxmstyle/commit/8821d22e
